apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gitea-backup
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/r-aas/k8s-platform
    targetRevision: main
    path: manifests/gitea-backup
  destination:
    server: https://kubernetes.default.svc
    namespace: git
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
    syncWaves:
      - 3